name: cc-checkin
# last updated: 20 Aug 2023

on:
  schedule:
    - cron: "0 3 * * *"
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: rukbate/cordcloud@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
